# One of 'error', 'warn', 'info', 'verbose', debug', 'silly'
# One of 'error', 'warn', 'info', 'verbose', debug', 'silly'
loglevel: 'debug'
ESlogging:
    enabled: true
    label: BLUEKNX2MQTT
    loglevel: warn
    options:
        indexPrefix: logs
        clientOpts:
            node: http://es.elastic.home
KNXESlogging:
    enabled: true
    label: BLUEKNX2MQTT
    loglevel: info
    options:
        indexPrefix: knx
        clientOpts:
            node: http://es.elastic.home
knx:
    # ETS exported group addresses
    etsExport: 'etsexport.csv'
    # Configuration passed to the KNX library
    options:
      ipAddr: '192.168.1.6'
      ipPort: 3671
mqtt:
    # URL to MQTT broker
    url: 'mqtt://jules.home'
    # Configuration passed to the MQTT library
    options:
        username: 'mqtt_username'
        password: 'mqtt_password'
    # Prefix to mqtt topic
    topicPrefix: 'knx'
